sudo: required
language: java
services:
  - docker
before_install:
  - mvn clean package
  - docker build -t envoys/mytask .
  - docker run -d -p 127.0.0.1:80:80 envoys/mytask /bin/sh -c "java -Djava.security.egd=file:/dev/./urandom -jar /mytask.jar"
  - docker ps -a
after_success:
  - docker tag envoys/mytask registry.heroku.com/peaceful-everglades-62328/web
  - docker login --username=_ --password="$HEROKUAUTHTOKEN" registry.heroku.com
  - docker push registry.heroku.com/peaceful-everglades-62328/web

