sudo: required
language: java


jdk:
  - oraclejdk8
services:
  - docker
install: true
script:
  - mvn clean package
  - docker build -t envoys/mytask .
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker tag envoys/mytask registry.heroku.com/peaceful-everglades-62328/web
  - docker login --username=_ --password="$HEROKUAUTHTOKEN" registry.heroku.com
  - docker push registry.heroku.com/peaceful-everglades-62328/web
